### ISSUE TITLE
Time to archive or remove this repo?

### ISSUE THREAD

**Issue by jobisoft** [thundernest/wetransfer-extension#3]
The service has long been discontinued. Does it make sense to keep this repository around?

**Comment by clokep** [comment]
I'd recommend archiving if it is dead. No reason to remove the code.

**Comment by jobisoft** [comment]
@malini : You are proposed to me as a peer who has the required rights to act on this repository.

We might just let the add-on sit here, but since it is no longer supported or maintained by us, it could be archived. What do you think?

**Comment by jobisoft** [comment]
A third option would be to move this from thunderbird org to thunderbird-community org, which clearly states that the code is not maintained by Thunderbird:

https://github.com/thunderbird-community

**Comment by Sancus** [comment]
I think archiving this is the right call. It will be done.
